#!/usr/bin/env ruby


def counting_dna_nucleotides(dna_string)
  dna_array = dna_string.chars.to_a
  g = dna_array.count { |n| n == 'G' }
  a = dna_array.count { |n| n == 'A' }
  c = dna_array.count { |n| n == 'C' }
  t = dna_array.count { |n| n == 'T' }
  puts "#{a} #{c} #{g} #{t}"
end

counting_dna_nucleotides("TTATGTTCCGGATATGCTATAGGGGTGGGATATGTACCGAGAATTATGAATCCGTGCTCGAACGTGGACACTTTAATGGTAACTCTATACCTTATGGTGTTGTCGTTTCAAGGAAGGGGATCCGTGATTAATATATCTGATACTACTGGATGAATCGCGCTGACAGACAGCGGAGTTTCTCGTGACAATTGGCCGAAATAAGCCTCCTGGCAGTGATCATCAATAACTAGTAGGTTCGTTTTAGGGCTACGGCGTAGTGTGGCGGTGTACAGTTTGGAACCCTTAGCTCCAAACGGAATCGGTAAACAAAAGAATCTAAGCCGAGTGCACCCCAGGGATCGCGATTTTACTGTTTCTGATAGCCACAAATAGGCGGGGAGCATACTCATTAGCAGCCAAGACCCGCCCACTCCCAATGTACGATCTGGAAGGACGGTTATGCTTTAGTCTTTGCTACGTATCACCTTGTCACCGAAATACATGGATAGCGGAACGCACGTCCCCATCGTTATACGGCTTGTGTAGGGACACTGCCCTATCACTTTGTGATATCCAGAAACAGGTCACGTACTAAGCACAATTGCTATACTTCTAAATGTCGGTCCGACGGGACCCGCCAGTTATCGACGAATGCGCTTAACCCCCCCGAACGCCTTTGGGCAATTCTCAGCTTTTCTACGTGAAACTCAATGGCCCAGTTCGATCTCTAGATGACATAGAGAGCTGAGATATGCGCTCCTTTGGCTGTGTAGATATCTGTTGAAGCATCCCGCGACCGTCCATTTCACGATCTCGTTGGGCGAGTTACTGAGACGGCACCTTCTTCACGGATAGATATTTCGTGTGTTGCCTATCGGGGACTATATAATCCATGCATGGTCACTCGCTTGTAAGGCAAAATTGCGTTTAAATTGATCCAACTCCGATCGGATTACATGGCCAAGTTGGAC") # => nil
# >> 240 223 230 257
